### ISSUE TITLE
被牆擋住了，當然一無所知^ ^

### ISSUE THREAD

**Issue by David-Tsui** [YellowDoing/China-vs-America#1]
可悲的土包子國
有5G有什麼用
還不是被檔

**Comment by YellowDoing** [comment]
你是台灣的吧，怕不是今年要被統一了

**Comment by David-Tsui** [comment]
怕不是你的腦子先給屎給統一了吧

**Comment by YellowDoing** [comment]
嘴里说的是中文，手上写的是汉字，不承认自己是中国人，可悲

**Comment by David-Tsui** [comment]
井底之蛙

**我們用的是繁體，不是像你們這種殘體，一點美感也沒有。**
**我們用的是繁體，不是像你們這種殘體，一點美感也沒有。**
**我們用的是繁體，不是像你們這種殘體，一點美感也沒有。**

**Comment by David-Tsui** [comment]
![image](https://user-images.githubusercontent.com/8610682/105651439-dfcfd100-5ef1-11eb-9292-c7eba8d8cea0.png)

**Comment by David-Tsui** [comment]
![image](https://user-images.githubusercontent.com/8610682/105651580-389f6980-5ef2-11eb-83e0-9bd63ad5bfef.png)
